const tenantCategories=[{id:'c1',name:'热菜',children:['大荤','小荤','半荤半素','素菜']},{id:'c2',name:'主食',children:['米饭','面食','点心']},{id:'c3',name:'汤粥',children:['汤类','粥类']}];
const tenantDishes=[
 {id:1,code:'ZC202608001',name:'红烧肉',category:'热菜 / 大荤',source:'自行创建',ingredients:6,status:'已上架',authorized:12,updated:'2026-08-25',newVersion:false},
 {id:2,code:'ZC202608002',name:'宫保鸡丁',category:'热菜 / 小荤',source:'标准菜品引用',ingredients:8,status:'已上架',authorized:8,updated:'2026-08-24',newVersion:true},
 {id:3,code:'ZC202608003',name:'紫菜蛋花汤',category:'汤粥 / 汤类',source:'标准菜品引用',ingredients:5,status:'已下架',authorized:0,updated:'2026-08-23',newVersion:false},
 {id:4,code:'ZC202608004',name:'青椒土豆丝',category:'热菜 / 素菜',source:'自行创建',ingredients:4,status:'已下架',authorized:0,updated:'2026-08-22',newVersion:false}
];
const standardDishes=[
 {id:'s1',code:'BZ20260018',name:'宫保鸡丁',category:'热菜 / 小荤',source:'平台标准菜品库',ingredients:8,status:'已引用',version:'V2.1',updated:'2026-08-26'},
 {id:'s2',code:'BZ20260035',name:'紫菜蛋花汤',category:'汤粥 / 汤类',source:'平台标准菜品库',ingredients:5,status:'已引用',version:'V1.3',updated:'2026-08-18'},
 {id:'s3',code:'BZ20260042',name:'清炒时蔬',category:'热菜 / 素菜',source:'教育营养菜品库',ingredients:4,status:'未引用',version:'V1.0',updated:'2026-08-15'},
 {id:'s4',code:'BZ20260057',name:'土豆烧牛肉',category:'热菜 / 大荤',source:'平台标准菜品库',ingredients:7,status:'未引用',version:'V1.2',updated:'2026-08-12'}
];
const authorizations=[
 {dish:'红烧肉',code:'ZC202608001',category:'热菜 / 大荤',merchants:['杭州市校园餐饮管理中心','西湖区学校后勤服务中心','南京未来教育服务中心'],count:12,updated:'2026-08-26'},
 {dish:'宫保鸡丁',code:'ZC202608002',category:'热菜 / 小荤',merchants:['杭州市校园餐饮管理中心','上海青禾校园服务中心'],count:8,updated:'2026-08-25'}
];
const dishPageHead=(title,desc,actions='')=>`<div class="page-head"><div><h1>${title}</h1><p>${desc}</p></div><div class="page-actions">${actions}</div></div>`;
const dishInfo=d=>`<div class="dish-info"><span class="dish-img">菜品</span><div><b>${d.name}${d.newVersion?'<span class="version-tag">有新版本</span>':''}</b><small>${d.code}</small></div></div>`;
function dishCenterPage(page){if(page==='dishes')return myDishPage();if(page==='standardDishes')return standardDishPage();if(page==='dishCategories')return categoryPage();return authorizationPage()}
function myDishPage(){return `<div class="dish-page">${dishPageHead('我的菜品库','维护租户自行创建或从标准菜品库引用的私域菜品','<button class="primary" id="createDish">＋ 新建菜品</button>')}<div class="dish-kpis"><div class="dish-kpi"><span>全部菜品</span><b>86</b></div><div class="dish-kpi"><span>已上架</span><b>62</b></div><div class="dish-kpi"><span>有上游新版本</span><b>3</b></div></div><div class="table-card"><div class="filters"><input id="dishKeyword" class="search" placeholder="⌕ 搜索菜品名称 / 编号"><select id="dishSource"><option value="">全部来源</option><option>自行创建</option><option>标准菜品引用</option></select><select id="dishState"><option value="">全部状态</option><option>已上架</option><option>已下架</option></select><select><option>全部分类</option><option>热菜 / 大荤</option><option>热菜 / 小荤</option><option>汤粥 / 汤类</option></select></div><table><thead><tr><th>菜品信息</th><th>分类</th><th>来源</th><th>用料数</th><th>状态</th><th>已授权商户</th><th>操作</th></tr></thead><tbody id="myDishBody">${tenantDishes.map(d=>myDishRow(d)).join('')}</tbody></table></div></div>`}
function myDishRow(d){return `<tr data-name="${d.name} ${d.code}" data-source="${d.source}" data-state="${d.status}"><td>${dishInfo(d)}</td><td>${d.category}</td><td><span class="source-tag ${d.source==='自行创建'?'self':''}">${d.source}</span></td><td>${d.ingredients}</td><td><span class="dish-status ${d.status==='已下架'?'off':''}">${d.status}</span></td><td><button class="link-btn dish-auth-detail" data-id="${d.id}">${d.authorized} 家</button></td><td class="dish-actions"><button class="link-btn dish-view" data-id="${d.id}">查看</button><button class="link-btn dish-edit" data-id="${d.id}">编辑</button><button class="link-btn dish-toggle" data-id="${d.id}">${d.status==='已上架'?'下架':'上架'}</button><button class="link-btn dish-delete" data-id="${d.id}">删除</button></td></tr>`}
function standardDishPage(){return `<div class="dish-page">${dishPageHead('标准菜品库','查看运营端授权使用的标准菜品，引用后进入我的菜品库','<button class="primary" id="batchReferenceDish">批量引用</button>')}<div class="readonly-banner">标准菜品由运营端授权，仅支持查看和引用，不可编辑、删除或上下架。</div><div class="table-card"><div class="filters"><input id="standardKeyword" class="search" placeholder="⌕ 搜索菜品名称 / 编号"><select id="standardRefState"><option value="">全部引用状态</option><option>未引用</option><option>已引用</option></select><select><option>全部标准分类</option><option>热菜 / 大荤</option><option>热菜 / 小荤</option><option>汤粥 / 汤类</option></select></div><table><thead><tr><th><input type="checkbox"></th><th>菜品信息</th><th>标准分类</th><th>授权来源</th><th>用料数</th><th>版本</th><th>引用状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody id="standardDishBody">${standardDishes.map(d=>`<tr data-name="${d.name} ${d.code}" data-state="${d.status}"><td><input class="standard-check" type="checkbox" value="${d.id}"></td><td>${dishInfo(d)}</td><td>${d.category}</td><td>${d.source}</td><td>${d.ingredients}</td><td>${d.version}</td><td><span class="dish-status ${d.status==='未引用'?'off':''}">${d.status}</span></td><td>${d.updated}</td><td><button class="link-btn standard-view" data-id="${d.id}">查看</button><button class="link-btn standard-reference" data-id="${d.id}">引用</button></td></tr>`).join('')}</tbody></table></div></div>`}
function categoryPage(){const rows=tenantCategories.flatMap((p,pi)=>[{name:p.name,level:'一级分类',parent:'-',count:p.children.length*6,sort:pi+1,status:'启用'},...p.children.map((c,ci)=>({name:c,level:'二级分类',parent:p.name,count:ci+2,sort:ci+1,status:'启用'}))]);return `<div class="dish-page">${dishPageHead('分类管理','自建一级、二级分类，用于租户创建或引用菜品','<button class="primary" id="newPrimaryCategory">＋ 新增一级分类</button>')}<div class="category-layout-v2"><aside class="category-tree-v2"><h3>分类结构</h3><div class="category-node-v2 active" data-category="all">全部分类 <span>${rows.length}</span></div>${tenantCategories.map(p=>`<div class="category-node-v2" data-category="${p.name}">▾ ${p.name}<span>${p.children.length}</span></div>${p.children.map(c=>`<div class="category-node-v2 child" data-category="${c}">${c}</div>`).join('')}`).join('')}</aside><section class="category-main-v2"><div class="category-main-head-v2"><h3 id="categoryTitleV2">全部分类</h3><button class="primary" id="newSecondaryCategory">＋ 新增二级分类</button></div><table><thead><tr><th>分类名称</th><th>层级</th><th>上级分类</th><th>菜品数量</th><th>排序</th><th>状态</th><th>操作</th></tr></thead><tbody id="categoryBodyV2">${rows.map(r=>`<tr data-category-row="${r.name}" data-parent="${r.parent}"><td><b>${r.name}</b></td><td>${r.level}</td><td>${r.parent}</td><td>${r.count}</td><td>${r.sort}</td><td><span class="dish-status">${r.status}</span></td><td><button class="link-btn category-edit">编辑</button><button class="link-btn category-toggle">停用</button><button class="link-btn category-delete">删除</button></td></tr>`).join('')}</tbody></table></section></div></div>`}
function authorizationPage(){return `<div class="dish-page">${dishPageHead('菜品授权','将我的菜品库中已上架的菜品授权给一个或多个商户','<button class="primary" id="newDishAuthorization">＋ 新增授权</button>')}<div class="table-card"><div class="dish-tabs"><button class="active" data-auth-view="dish">按菜品查看</button><button data-auth-view="merchant">按商户查看</button></div><div class="filters"><input class="search" id="authKeyword" placeholder="⌕ 搜索菜品 / 商户"><div class="auth-view-switch"><button class="active">全部授权</button><button>近期新增</button></div></div><div id="authorizationTable">${authorizationByDish()}</div></div></div>`}
function authorizationByDish(){return `<table><thead><tr><th>菜品信息</th><th>分类</th><th>授权商户</th><th>授权商户数</th><th>更新时间</th><th>操作</th></tr></thead><tbody>${authorizations.map((a,i)=>`<tr><td><b>${a.dish}</b><span class="sub">${a.code}</span></td><td>${a.category}</td><td><div class="merchant-pills">${a.merchants.slice(0,2).map(x=>`<span>${x}</span>`).join('')}${a.count>2?`<span>+${a.count-2}</span>`:''}</div></td><td>${a.count} 家</td><td>${a.updated}</td><td><button class="link-btn auth-edit" data-index="${i}">新增/删除商户</button><button class="link-btn auth-remove" data-index="${i}">解除授权</button></td></tr>`).join('')}</tbody></table>`}
function authorizationByMerchant(){return `<table><thead><tr><th>商户</th><th>业态模板</th><th>已授权菜品</th><th>菜品数</th><th>更新时间</th><th>操作</th></tr></thead><tbody><tr><td><b>杭州市校园餐饮管理中心</b><span class="sub">hzxycy</span></td><td>K12 教育业态</td><td><div class="merchant-pills"><span>红烧肉</span><span>宫保鸡丁</span></div></td><td>16 个</td><td>2026-08-26</td><td><button class="link-btn auth-edit">新增/删除菜品</button></td></tr><tr><td><b>西湖区学校后勤服务中心</b><span class="sub">xhxxhq</span></td><td>K12 教育业态</td><td><div class="merchant-pills"><span>红烧肉</span></div></td><td>8 个</td><td>2026-08-25</td><td><button class="link-btn auth-edit">新增/删除菜品</button></td></tr></tbody></table>`}
function dishDrawer(title,body,save='保存'){document.querySelector('#dishDrawerMask')?.remove();document.body.insertAdjacentHTML('beforeend',`<div id="dishDrawerMask" class="modal"><div class="modal-card dish-drawer"><div class="modal-head"><div><h3>${title}</h3><p>菜品中心 · 租户私域数据</p></div><button class="dish-drawer-close">×</button></div>${body}<div class="editor-footer"><button class="ghost dish-drawer-close">取消</button>${save?`<button id="dishDrawerSave" class="primary">${save}</button>`:''}</div></div></div>`);$$('.dish-drawer-close').forEach(b=>b.onclick=()=>$('#dishDrawerMask').remove())}
function dishEditor(d=null,readonly=false){dishDrawer(readonly?'查看菜品':d?'编辑菜品':'新建菜品',`<div class="dish-form-section"><h4>一、基本信息</h4><div class="dish-form-grid"><label>菜品编号<input value="${d?.code||'系统自动生成'}" disabled></label><label>菜品名称<input value="${d?.name||''}" ${readonly?'disabled':''}></label></div></div><div class="dish-form-section"><h4>二、用料明细</h4></div><div class="dish-form-section"><h4>三、烹饪工艺与制作步骤</h4></div><div class="dish-form-section"><h4>四、营养预览</h4></div>`,readonly?'':'保存草稿')}
function standardDetail(d){dishDrawer('标准菜品详情',`<div class="readonly-banner">标准菜品为只读内容，引用后可进入我的菜品库维护。</div><div class="dish-form-section"><h4>一、基本信息</h4><div class="dish-form-grid"><label>标准菜品编号<input value="${d.code}" disabled></label><label>菜品名称<input value="${d.name}" disabled></label></div></div><div class="dish-form-section"><h4>二、用料明细</h4></div><div class="dish-form-section"><h4>三、烹饪工艺与制作步骤</h4></div><div class="dish-form-section"><h4>四、营养预览</h4></div>`,'')}
function referenceDrawer(items){const groups=[...new Map(items.map(d=>[d.category,{category:d.category,items:items.filter(x=>x.category===d.category)}])).values()],options='<option value="">请选择自建二级分类</option><option>热菜 / 大荤</option><option>热菜 / 小荤</option><option>热菜 / 素菜</option><option>汤粥 / 汤类</option>';dishDrawer(`引用标准菜品（${items.length}个）`,`<div class="flow-steps"><span class="active">1 选择菜品</span><span class="active">2 指定分类</span><span>3 引用完成</span></div><div class="readonly-banner">引用后在“我的菜品库”生成独立私域副本，默认为下架状态。</div>${items.length>1?'<div class="reference-mode-tabs"><button class="active" data-reference-mode="item">按菜品指定分类</button><button data-reference-mode="category">按源分类批量映射</button></div>':''}<div id="itemMapping" class="mapping-box">${items.map(d=>`<div class="mapping-row"><div><b>${d.name}</b><small>${d.category} · ${d.code}</small></div><span>存入</span><select class="reference-category">${options}</select></div>`).join('')}</div>${items.length>1?`<div id="categoryMapping" class="mapping-box" hidden>${groups.map(g=>`<div class="mapping-row"><div><b>${g.category}</b><small>该源分类下已选择 ${g.items.length} 个菜品</small></div><span>批量存入</span><select class="reference-group-category">${options}</select></div>`).join('')}</div>`:''}`,'确认引用');$$('[data-reference-mode]').forEach(b=>b.onclick=()=>{$$('[data-reference-mode]').forEach(x=>x.classList.toggle('active',x===b));const byCategory=b.dataset.referenceMode==='category';$('#itemMapping').hidden=byCategory;$('#categoryMapping').hidden=!byCategory});$('#dishDrawerSave').onclick=()=>{const activeSelects=$('#categoryMapping')&&!$('#categoryMapping').hidden?$$('.reference-group-category'):$$('.reference-category');if([...activeSelects].some(s=>!s.value))return showToast('请完成全部分类映射');$('#dishDrawerMask').remove();showToast(`成功引用 ${items.length} 个菜品，已生成下架草稿`)}}
function categoryEditor(level){dishDrawer(`新增${level}`,`<div class="dish-form-section"><div class="dish-form-grid"><label>分类层级<input value="${level}" disabled></label>${level==='二级分类'?'<label>上级分类<select><option>热菜</option><option>主食</option><option>汤粥</option></select></label>':''}<label>分类名称<input id="newCategoryName" placeholder="请输入分类名称"></label><label>排序值<input type="number" value="1"></label></div></div>`,'确认创建');$('#dishDrawerSave').onclick=()=>{if(!$('#newCategoryName').value.trim())return showToast('请输入分类名称');$('#dishDrawerMask').remove();showToast(`${level}创建成功`)}}
function authorizationDrawer(){dishDrawer('新增菜品授权',`<div class="flow-steps"><span class="active">1 选择菜品</span><span class="active">2 选择商户</span><span>3 确认授权</span></div><div class="dish-form-section"><h4>选择菜品</h4><p>仅展示已上架的菜品</p><div class="select-list">${tenantDishes.filter(d=>d.status==='已上架').map(d=>`<div class="select-row"><input type="checkbox" class="auth-dish-check"><label><b>${d.name}</b><small>${d.code} · ${d.category}</small></label></div>`).join('')}</div></div><div class="dish-form-section"><h4>选择商户</h4><p>支持同时授权给一个或多个商户，不设置授权有效期</p><div class="select-list">${merchantRows.slice(0,4).map(m=>`<div class="select-row"><input type="checkbox" class="auth-merchant-check"><label><b>${m[0]}</b><small>${m[1]} · ${m[4]}</small></label></div>`).join('')}</div></div><div class="readonly-banner">商户只能查看被授权的源菜品，必须先引用到商户私域菜品库后才能编辑和使用。</div>`,'确认授权');$('#dishDrawerSave').onclick=()=>{if(!$$('.auth-dish-check:checked').length)return showToast('请至少选择一个菜品');if(!$$('.auth-merchant-check:checked').length)return showToast('请至少选择一个商户');$('#dishDrawerMask').remove();showToast('菜品授权成功')}}
function bindDishCenter(page){if(page==='dishes'){const filter=()=>{const k=$('#dishKeyword').value.toLowerCase(),s=$('#dishSource').value,st=$('#dishState').value;$$('#myDishBody tr').forEach(r=>r.style.display=(!k||r.dataset.name.toLowerCase().includes(k))&&(!s||r.dataset.source===s)&&(!st||r.dataset.state===st)?'':'none')};$('#dishKeyword').oninput=filter;$('#dishSource').onchange=filter;$('#dishState').onchange=filter;$('#createDish').onclick=()=>dishEditor();$$('.dish-view').forEach(b=>b.onclick=()=>{const d=tenantDishes.find(x=>x.id==b.dataset.id);d.newVersion?versionedDishView(d):dishEditor(d,true)});$$('.dish-edit').forEach(b=>b.onclick=()=>dishEditor(tenantDishes.find(d=>d.id==b.dataset.id)));$$('.dish-toggle').forEach(b=>b.onclick=()=>{const d=tenantDishes.find(x=>x.id==b.dataset.id);d.status=d.status==='已上架'?'已下架':'已上架';showToast(`菜品已${d.status}`);render('dishes')});$$('.dish-delete').forEach(b=>b.onclick=()=>{const d=tenantDishes.find(x=>x.id==b.dataset.id);showToast(d.authorized?'请先解除全部商户授权后再删除':'菜品已删除')});$$('.dish-auth-detail').forEach(b=>b.onclick=authorizationDrawer)}
 if(page==='standardDishes'){const filter=()=>{const k=$('#standardKeyword').value.toLowerCase(),s=$('#standardRefState').value;$$('#standardDishBody tr').forEach(r=>r.style.display=(!k||r.dataset.name.toLowerCase().includes(k))&&(!s||r.dataset.state===s)?'':'none')};$('#standardKeyword').oninput=filter;$('#standardRefState').onchange=filter;$$('.standard-view').forEach(b=>b.onclick=()=>standardDetail(standardDishes.find(d=>d.id===b.dataset.id)));$$('.standard-reference').forEach(b=>b.onclick=()=>referenceDrawer([standardDishes.find(d=>d.id===b.dataset.id)]));$('#batchReferenceDish').onclick=()=>{const rows=standardDishes.filter(d=>[...$$('.standard-check:checked')].some(c=>c.value===d.id));rows.length?referenceDrawer(rows):showToast('请先选择需要引用的标准菜品')}}
 if(page==='dishCategories'){$$('.category-node-v2').forEach(n=>n.onclick=()=>{$$('.category-node-v2').forEach(x=>x.classList.toggle('active',x===n));$('#categoryTitleV2').textContent=n.dataset.category;$$('#categoryBodyV2 tr').forEach(r=>r.style.display=n.dataset.category==='all'||r.dataset.categoryRow===n.dataset.category||r.dataset.parent===n.dataset.category?'':'none')});$('#newPrimaryCategory').onclick=()=>categoryEditor('一级分类');$('#newSecondaryCategory').onclick=()=>categoryEditor('二级分类');$$('.category-edit').forEach(b=>b.onclick=()=>categoryEditor(b.closest('tr').children[1].textContent));$$('.category-toggle').forEach(b=>b.onclick=()=>showToast('分类状态已更新'));$$('.category-delete').forEach(b=>b.onclick=()=>showToast('已使用的分类不能删除'))}
 if(page==='dishAuthorization'){$$('[data-auth-view]').forEach(b=>b.onclick=()=>{$$('[data-auth-view]').forEach(x=>x.classList.toggle('active',x===b));$('#authorizationTable').innerHTML=b.dataset.authView==='dish'?authorizationByDish():authorizationByMerchant();bindAuthActions()});$('#newDishAuthorization').onclick=authorizationDrawer;bindAuthActions()}}
function bindAuthActions(){$$('.auth-edit').forEach(b=>b.onclick=authorizationDrawer);$$('.auth-remove').forEach(b=>b.onclick=()=>showToast('已解除所选授权；商户已引用的私域副本不受影响'))}
